### ISSUE TITLE
Allow data loading from compressed URLs (Zip, GZip)

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#209]
**Current behavior**: Files that are in a loadable format (CSV, TXT, etc...), but compressed (Zip, GZip) can not presently be loaded directly into Vizier.  If a link to a compressed file is available, the file must first be downloaded locally or exposed at a decompressed URL.  

**Desired behavior**: Allow users to provide *Load from the Internet* links to compressed files.  If necessary, add a checkbox/pop-up to specify compression as a parameter (although preferably, this would be autodetected from `Content-Type`, the file extension, or similar)

**Comment by okennedy** [comment]
@mrb24 says : I implemented this already, but it may not be integrated yet.

**Comment by mrb24** [comment]
For zipped file support you need to supply one of the following to the load cell "compression" option if the file does not have the extension in the filename:

name     | ext          | codec class
-------------------------------------------------------------
bzip2     | .bz2        | org.apache.hadoop.io.compress.BZip2Codec 
default   | .deflate   | org.apache.hadoop.io.compress.DefaultCodec 
deflate   | .deflate   | org.apache.hadoop.io.compress.DeflateCodec 
gzip       | .gz          | org.apache.hadoop.io.compress.GzipCodec 
lz4         | .lz4         | org.apache.hadoop.io.compress.Lz4Codec 
snappy  | .snappy  | org.apache.hadoop.io.compress.SnappyCodec

.zip extension not supported because it can not be partitioned.  if we want support for that for smaller files we'll need to implement it in Load or Stage of mimir-api
