### ISSUE TITLE
Allow Caveat annotation from SQL

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#212]
Just a matter of registering a Caveat function to Spark and then adding a preprocessing step that translates calls to the caveat function into ApplyCaveat expressions.

**Comment by lordpretzel** [comment]
Got the `mimir-caveats` side of this implemented and tested. Currently, calls to `Caveat` are not dealt with in a separate preprocessing step, but are rewritten in the expression rewrites like the `ApplyCaveat` expressions themselves. Will work no the `mimir-api` integration next.

Spark does not allow `Any` as a return type. So for now the function is retuning `String`. This is not a problem, because it is never executed.

**Comment by okennedy** [comment]
Re: Function return type: I've gone down the "Hack an ANY type in" road before several times, and it always ends in pain and suffering.  Have you tried making the `dataType` property of the function a lazy computed value derived from the `dataType` of the pass-through argument?

**Comment by lordpretzel** [comment]
The code example you are showing is creating a new type of expression. We already have that for the DF API (albeit not lazy datatypes). The problem is that to be able to access caveats from SQL we have to register it is a UDF with Spark though a particular API. Then we can use it from SQL. This UDF registration does not allow for overloading of functions (the new function replaces the old one). Ways forward I see:

- different function names based on data type
- look a workaround using Hive UDFs: I read that it is possible to register the functions as Hive UDFs to allow overloading [(https://blog.knoldus.com/udf-overloading-in-spark/)](https://blog.knoldus.com/udf-overloading-in-spark/)
- look into whether we can hack early enough into the semantic analysis in Spark to replace such functions before they can cause trouble
- look into we can hack into the UDF registration framework

anyways, I think for now it works having a function `Any => String` and we can replace this afterwards if one of the other options pan out.

~~~sh
scala> val fint =  (a: Int) => a + 1
fint: Int => Int = $Lambda$2771/0x00000008011c7040@2c4fe25e

scala> val fstring =  (a: String) => a
fstring: String => String = $Lambda$2772/0x00000008011c6840@70c38e0

scala> spark.udf.register("f", fstring)
res11: org.apache.spark.sql.expressions.UserDefinedFunction = SparkUserDefinedFunction($Lambda$2772/0x00000008011c6840@70c38e0,StringType,List(Some(class[value[0]: string])),Some(f),true,true)

scala> spark.udf.register("f", fint)
20/08/01 18:10:57 WARN SimpleFunctionRegistry: The function f replaced a previously registered function.
res12: org.apache.spark.sql.expressions.UserDefinedFunction = SparkUserDefinedFunction($Lambda$2771/0x00000008011c7040@2c4fe25e,IntegerType,List(Some(class[value[0]: int])),Some(f),false,true)

scala>
~~~

**Comment by lordpretzel** [comment]
Spark's function registry allow arbitrary expression transformers `Seq[Expression] => Expression` to be registered. When a UDF of that name is applied, then during analysis the transformer is called to replaces the inputs of the expression (the `Seq[Expression]` with the return value of the transformer. We use this to replace calls to the `Caveat` UDF with our own `ApplyCaveat` expression.
