### ISSUE TITLE
Large Data Sets time out while loading

### ISSUE THREAD

**Issue by okennedy** [VizierDB/web-ui#37]
Short term fix: **Increase front-end API timeout**

Long term fix: **Handle data set loading asynchronously**

**Comment by mrb24** [comment]
fixed by commits:
commit: VizierDB/web-api@7e14639
commit: VizierDB/web-api@0dbe637
commit: VizierDB/web-api@28dc460
commit: VizierDB/web-api@b7e36f5
commit: VizierDB/web-api@8d9a1d7
commit: VizierDB/web-api@28dc460
commit: UBOdin/mimir@721d54d
commit: UBOdin/mimir@d9a9ef3
commit: UBOdin/mimir@f44fb4a
